services:
  - type: web
    name: tradepro-finder-toronto
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install gunicorn
      mkdir -p logs data generated_pages
      python generate_seo_pages.py
    startCommand: gunicorn wsgi:flask_instance --timeout 120
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: wsgi.py
      - key: PYTHONUNBUFFERED
        value: true
      - key: GOOGLE_PLACES_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: data
      mountPath: /opt/render/project/data
      mountPath: /data
      sizeGB: 1
    domains:
      - tradepro-finder-canada.onrender.com
