services:
  - type: web
    name: tradepro-finder-toronto
    env: python
    buildCommand: |
      # Install dependencies
      pip install -r requirements.txt
      # Create necessary directories
      mkdir -p logs
      mkdir -p data
      # Touch log files to prevent errors
      touch logs/app.log
      touch logs/error.log
      touch logs/access.log
      # Ensure logs are writable
      chmod -R 777 logs || true
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: application.py
      - key: GOOGLE_PLACES_API_KEY
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    domains:
      - tradepro-finder-canada.onrender.com
